version: '2'
services:
    jhipsterrwa-app:
        image: jhipsterrwa
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipsterrwa-postgresql:5432/jhipsterrwa
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipsterrwa-postgresql:
        extends:
            file: postgresql.yml
            service: jhipsterrwa-postgresql
