version: '2'
services:
    jhipsterrwa-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/jhipsterrwa/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=jhipsterrwa
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
